"""Deterministic authored synthetic labels, never labels generated by Gemma.

Splits have disjoint template families, entity names and numeric inventories.
Each group includes an equivalence pair and a critical semantic contrast.
"""
import json
from pathlib import Path
from gateway.typed_event_graph import VERSION, ROLES, validate_graph
from gateway.event_graph_extractor import prompt, quote_only

ROOT = Path(__file__).parent
FAMILIES = ("quantity", "comparator", "polarity", "recipient", "authority", "unless", "nested", "direction", "temporal", "revision", "time", "paragraph", "approval", "nested_boolean", "negation_scope", "conflict", "multi_quantity", "unit_equivalence")


class Builder:
    def __init__(self, text):
        self.text = text
        self.graph = {"version": VERSION, **{k: [] for k in ("entities", "predicates", "conditions", "events", "links", "unresolved")}}

    def ev(self, quote):
        # Longer source quote is required if the exact surface occurs repeatedly.
        if self.text.count(quote) != 1:
            quote = self.text
        start = self.text.index(quote)
        return [{"start": start, "end": start + len(quote), "quote": quote}]

    def entity(self, name):
        key = f"n{len(self.graph['entities']) + 1}"
        self.graph["entities"].append({"id": key, "name": name, "mentions": self.ev(name)})
        return key

    def predicate(self, subject, value, unit, comparator, quote, negated=False):
        key = f"p{len(self.graph['predicates']) + 1}"
        self.graph["predicates"].append(dict(id=key, subject=subject, value=str(value), unit=unit, comparator=comparator, negated=negated, evidence=self.ev(quote)))
        return key

    def condition(self, operator, args):
        key = f"c{len(self.graph['conditions']) + 1}"
        self.graph["conditions"].append(dict(id=key, operator=operator, args=args, evidence=self.ev(self.text)))
        return key

    def event(self, action, *, roles=None, condition=None, exception=None, complement=None, modality="obligation", negated=False, revision=None, time=None, quote=None):
        key = f"e{len(self.graph['events']) + 1}"
        self.graph["events"].append(dict(id=key, action=action, roles={**dict.fromkeys(ROLES), **(roles or {})},
            modality=modality, negated=negated, condition=condition, exception=exception, complement=complement,
            revision=None if revision is None else {"value": revision, "evidence": self.ev(revision)},
            time=None if time is None else {"value": time, "evidence": self.ev(time)}, evidence=self.ev(quote or self.text)))
        return key

    def link(self, kind, source, target):
        self.graph["links"].append(dict(id=f"l{len(self.graph['links'])+1}", kind=kind, source=source, target=target, evidence=self.ev(self.text)))


def case(split, family, index, variant):
    # 0 canonical, 1 fresh paraphrase, 2 changed meaning.
    style = {"train": 0, "dev": 1, "heldout": 2}[split]
    prefix = ("Aster", "Birch", "Cobalt")[style]
    a, b, c = f"{prefix} works {index}", f"{prefix} monitor {index}", f"{prefix} officer {index}"
    value = ((100, 300, 500, 700, 900, 1100, 1300, 1500) if style == 0 else
             (127, 347, 563, 787) if style == 1 else (193, 419, 631, 857))[index % (8 if style == 0 else 4)]
    changed, para = variant == 2, variant == 1
    if family in ("quantity", "comparator", "polarity"):
        amount = value + 17 if changed and family == "quantity" else value
        op = "LE" if changed and family == "comparator" else "GT"
        bound = "is at most" if op == "LE" else ("is greater than" if para else "exceeds")
        neg = changed and family == "polarity"
        action = "must not stop" if neg else ("is required to stop" if para else "must stop")
        text = (f"If {b} {bound} {amount} mm/s, {a} {action}.",
                f"{a} {action} whenever {b} {bound} {amount} mm/s.",
                f"The following rule applies to {a}: it {action} in the event that {b} {bound} {amount} mm/s.")[style]
        g = Builder(text); actor = g.entity(a); monitor = g.entity(b)
        pred = g.predicate(monitor, amount, "mm/s", op, f"{b} {bound} {amount} mm/s")
        g.event("stop", roles={"object": actor}, condition=pred, negated=neg)
    elif family in ("recipient", "authority"):
        authority = family == "authority"
        name = c + (" alternate" if changed else "")
        subject = f"By order of {name}, " if authority else ""
        notify = "" if authority else f" {name} must be notified under the same condition."
        lead = (f"if {b} exceeds {value} mm/s", f"when {b} is greater than {value} mm/s", f"on a reading of {b} above {value} mm/s")[style]
        action = "is required to stop" if para else "must stop"
        text = f"{subject}{a} {action} {lead}.{notify}"
        g = Builder(text); works = g.entity(a); monitor = g.entity(b); person = g.entity(name)
        pred = g.predicate(monitor, value, "mm/s", "GT", lead)
        g.event("stop", roles={"object": works, **({"authority": person} if authority else {})}, condition=pred)
        if not authority:
            g.event("notify", roles={"recipient": person}, condition=pred)
    elif family == "unless":
        # Exception is a separately scoped measurable predicate; no invented approval.
        limit = value + 17 if changed else value
        phrase = "is permitted to continue" if para else "may continue"
        text = (f"{a} {phrase} unless {b} exceeds {limit} mm/s.",
                f"Unless {b} is greater than {limit} mm/s, {a} {phrase}.",
                f"{a} {phrase}; the exception is a reading of {b} above {limit} mm/s.")[style]
        g = Builder(text); works = g.entity(a); monitor = g.entity(b)
        pred = g.predicate(monitor, limit, "mm/s", "GT", text)
        g.event("continue", roles={"object": works}, modality="permission", exception=pred)
    elif family == "nested":
        join = "or" if changed else "and"
        bound = "is greater than" if para else "exceeds"
        text = (f"If {b} {bound} {value} mm/s {join} {c} is below 2 m, {a} must stop.",
                f"{a} must stop when {b} {bound} {value} mm/s {join} {c} is below 2 m.",
                f"For {a}, stopping is mandatory under this test: {b} {bound} {value} mm/s {join} {c} is below 2 m.")[style]
        g = Builder(text); works = g.entity(a); monitor = g.entity(b); other = g.entity(c)
        p = g.predicate(monitor, value, "mm/s", "GT", f"{b} {bound} {value} mm/s")
        q = g.predicate(other, 2, "m", "LT", f"{c} is below 2 m")
        cond = g.condition("any" if changed else "all", [p, q])
        g.event("stop", roles={"object": works}, condition=cond)
    elif family == "direction":
        src, dst = (b, a) if changed else (a, b)
        text = (f"{dst} is caused by {src}." if para else f"{src} causes {dst}.") if style == 0 else (
            f"The cause of {dst} is {src}." if style == 1 else f"{dst} results from {src}.")
        g = Builder(text); source = g.entity(src); target = g.entity(dst)
        g.event("cause", roles={"source": source, "target": target}, modality="assertion")
    elif family == "temporal":
        temporal = "after" if changed else "before"
        text = (f"{a} must inspect {b} {temporal} {c} may continue.",
                f"Inspection of {b} by {a} is required {temporal} continuation of {c} is permitted.",
                f"{a} is obliged to inspect {b}; this must occur {temporal} {c} is allowed to continue.")[style]
        if para:
            text = text.replace("must inspect", "is required to inspect").replace("is obliged", "is required")
        g = Builder(text); actor = g.entity(a); obj = g.entity(b); works = g.entity(c)
        first = g.event("inspect", roles={"actor": actor, "object": obj})
        second = g.event("continue", roles={"object": works}, modality="permission")
        g.link(temporal, first, second)
    elif family == "revision":
        old, new = f"R-{prefix}-{index}-A", f"R-{prefix}-{index}-" + ("C" if changed else "B")
        text = (f"Revision {old} requires {a} to stop. Revision {new} supersedes it and permits {a} to continue.",
                f"Under revision {old}, {a} must stop. Its replacement, revision {new}, allows {a} to continue.",
                f"{a} is obliged to stop in revision {old}; that requirement is superseded by revision {new}, permitting {a} to continue.")[style]
        if para:
            text = text.replace("permits", "allows").replace("must stop", "is required to stop")
        g = Builder(text); works = g.entity(a)
        first = g.event("stop", roles={"object": works}, revision=old)
        second = g.event("continue", roles={"object": works}, modality="permission", revision=new)
        g.link("supersedes", second, first)
    elif family == "time":
        date = f"{2027+style}-10-{(index % 20) + (2 if changed else 1):02d}"
        text = (f"On {date}, {a} must inspect {b}.", f"{a} is required to inspect {b} on {date}.", f"The inspection of {b} by {a} is mandatory on {date}.")[style]
        if para:
            text = text.replace("must inspect", "is required to inspect").replace("mandatory", "required")
        g = Builder(text); actor = g.entity(a); obj = g.entity(b)
        g.event("inspect", roles={"actor": actor, "object": obj}, time=date)
    elif family == "approval":
        person = c + (" alternate" if changed else "")
        text = (f"{a} may continue unless {person} approves stopping {a}.",
                f"Continuation of {a} is allowed except when {person} approves its stoppage.",
                f"{a} is permitted to continue, subject to this exception: {person} approves stopping it.")[style]
        g = Builder(text); works = g.entity(a); authority = g.entity(person)
        first = g.event("continue", roles={"object": works}, modality="permission", exception="e2")
        second = g.event("approve", roles={"actor": authority}, modality="hypothetical", complement="e3")
        g.event("stop", roles={"object": works}, modality="hypothetical")
    elif family in ("nested_boolean", "negation_scope"):
        d = f"{prefix} gauge {index}"
        top = "or" if changed and family == "nested_boolean" else "and"
        negated = family == "negation_scope" and changed
        condition_text = f"{b} is {'not ' if negated else ''}above {value} mm/s"
        text = (f"{a} must stop if {condition_text} {top} either {c} is below 2 m or {d} is above 3 m.",
                f"Stopping {a} is required when {condition_text} {top} ({c} is below 2 m or {d} is above 3 m).",
                f"The stop rule for {a} is mandatory: {condition_text} {top} at least one of these holds: {c} is below 2 m; {d} is above 3 m.")[style]
        g = Builder(text); works = g.entity(a); one = g.entity(b); two = g.entity(c); three = g.entity(d)
        p1 = g.predicate(one, value, "mm/s", "GT", condition_text, negated=negated)
        p2 = g.predicate(two, 2, "m", "LT", f"{c} is below 2 m")
        p3 = g.predicate(three, 3, "m", "GT", f"{d} is above 3 m")
        inner = g.condition("any", [p2, p3]); outer = g.condition("any" if top == "or" else "all", [p1, inner])
        g.event("stop", roles={"object": works}, condition=outer)
    elif family == "conflict":
        last = "may continue" if changed else "must not stop"
        text = (f"{a} must stop. A conflicting instruction says {a} {last}.",
                f"Stopping {a} is required; a conflicting rule says {a} {last}.",
                f"One rule requires {a} to stop, whereas its conflicting counterpart says {a} {last}.")[style]
        g = Builder(text); works = g.entity(a)
        first = g.event("stop", roles={"object": works})
        second = g.event("continue" if changed else "stop", roles={"object": works}, modality="permission" if changed else "obligation", negated=not changed)
        g.link("conflicts", first, second)
    elif family == "multi_quantity":
        first_value, second_value = (value+17, value) if changed else (value, value+17)
        text = (f"{a} must stop if {b} exceeds {first_value} mm/s. Notify {c} if {b} exceeds {second_value} mm/s.",
                f"Above {first_value} mm/s on {b}, {a} must stop; above {second_value} mm/s on that same monitor, notification to {c} is required.",
                f"The stop threshold for {a} is a reading of {b} greater than {first_value} mm/s. The requirement to notify {c} has its own threshold: the same reading must exceed {second_value} mm/s.")[style]
        g = Builder(text); works = g.entity(a); monitor = g.entity(b); person = g.entity(c)
        p1 = g.predicate(monitor, first_value, "mm/s", "GT", text); p2 = g.predicate(monitor, second_value, "mm/s", "GT", text)
        g.event("stop", roles={"object": works}, condition=p1); g.event("notify", roles={"recipient": person}, condition=p2)
    elif family == "unit_equivalence":
        amount, unit = (str(value * 1000), "mm") if para else (str(value + (17 if changed else 0)), "m")
        text = (f"{a} must stop if {b} exceeds {amount} {unit}.",
                f"{a} is required to stop with {b} greater than {amount} {unit}.",
                f"Stopping {a} becomes mandatory on a reading of {b} above {amount} {unit}.")[style]
        g = Builder(text); works = g.entity(a); monitor = g.entity(b)
        p1 = g.predicate(monitor, amount, unit, "GT", text)
        g.event("stop", roles={"object": works}, condition=p1)
    else:
        limit = value + 17 if changed else value
        d = f"{prefix} discharge {index}"
        text = (f"{a} may continue while {b} is below {value} mm/s. If that reading exceeds {value} mm/s, {a} must stop and {c} must be notified. {d} is limited to {limit} L/min.",
                f"Continuation of {a} is permitted provided {b} remains below {value} mm/s. Above {value} mm/s on that monitor, stopping {a} and notifying {c} are required. {d} may run at no more than {limit} L/min.",
                f"Regarding {a}, continued operation is allowed with {b} below {value} mm/s. Should the same monitor exceed {value} mm/s, {a} is required to stop; notification to {c} is also mandatory. The allowed rate for {d} is at most {limit} L/min.")[style]
        if para:
            text = text.replace("must be notified", "is required to be notified").replace("limited to", "capped at").replace("mandatory", "required")
        g = Builder(text); works = g.entity(a); monitor = g.entity(b); recipient = g.entity(c); discharge = g.entity(d)
        low = g.predicate(monitor, value, "mm/s", "LT", text)
        high = g.predicate(monitor, value, "mm/s", "GT", text)
        cap = g.predicate(discharge, limit, "L/min", "LE", text)
        g.event("continue", roles={"object": works}, modality="permission", condition=low)
        g.event("stop", roles={"object": works}, condition=high)
        g.event("notify", roles={"recipient": recipient}, condition=high)
        g.event("discharge", roles={"object": discharge}, modality="permission", condition=cap)
    # Distinct prose even where a family uses a shared surface within a split.
    if para and family not in ("quantity", "comparator", "polarity", "unit_equivalence"):
        prefix_text = ("For this operation, ", "In the project instructions, ", "The site note states: ")[style]
        text = prefix_text + text
        for table in g.graph.values():
            if isinstance(table, list):
                def shift(item):
                    if isinstance(item, dict):
                        if "start" in item:
                            item["start"] += len(prefix_text); item["end"] += len(prefix_text)
                        for child in item.values(): shift(child)
                    elif isinstance(item, list):
                        for child in item: shift(child)
                shift(table)
    validate_graph(g.graph, text)
    return {"id": f"{split}-{family}-{index}-{variant}", "group": f"{split}-{family}-{index}", "family": family,
            "variant": ("canonical", "paraphrase", "contrast")[variant], "source": text, "graph": g.graph}


def build():
    ROOT.joinpath("data").mkdir(exist_ok=True)
    for split, size in (("train", 8), ("dev", 2), ("heldout", 2)):
        rows = [case(split, family, index, variant) for family in FAMILIES for index in range(size) for variant in range(3)]
        ROOT.joinpath("data", f"{split}.jsonl").write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows))
    # Only train and dev are exposed to the training library. No test.jsonl here.
    ROOT.joinpath("training").mkdir(exist_ok=True)
    for split, name in (("train", "train"), ("dev", "valid")):
        rows = [json.loads(line) for line in ROOT.joinpath("data", f"{split}.jsonl").read_text().splitlines()]
        payload = [{"messages": [{"role": "user", "content": prompt(r["source"])},
                                  {"role": "assistant", "content": json.dumps(quote_only(r["graph"]), separators=(",", ":"))}]} for r in rows]
        ROOT.joinpath("training", f"{name}.jsonl").write_text("".join(json.dumps(r) + "\n" for r in payload))

if __name__ == "__main__":
    build()
