import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/preact";
import { webcrypto } from "node:crypto";
import { afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { App } from "../src/App";
import { FakeDesktopBackend } from "../src/fakeBackend";

beforeAll(() => {
  Object.defineProperty(globalThis, "crypto", { configurable: true, value: webcrypto });
});
afterEach(cleanup);

describe("desktop project → capture → supersede → audit smoke", () => {
  it("keeps every transition visible and auditable", async () => {
    render(<App backend={new FakeDesktopBackend()}/>);
    await screen.findByRole("heading", { name: "Local Release Console" });
    fireEvent.click(screen.getByRole("button", { name: /new project/i }));
    await screen.findByRole("heading", { name: "New Project" });
    fireEvent.click(screen.getByRole("button", { name: /quick capture decision/i }));
    fireEvent.click(screen.getByRole("button", { name: "Ledger" }));
    await screen.findByRole("heading", { name: "Document user-gated workflow" });
    fireEvent.click(screen.getByRole("button", { name: /supersede with reason/i }));
    await screen.findByRole("heading", { name: "Document user-gated workflow · revised" });
    expect(screen.getAllByText("superseded").length).toBeGreaterThan(0);
    fireEvent.click(screen.getByRole("button", { name: "Audit" }));
    await waitFor(() => expect(screen.getByText("STATE_SUPERSEDED")).toBeTruthy());
  });
  it("saves front-row and conflict teaching settings per project", async () => {
    const backend = new FakeDesktopBackend();
    render(<App backend={backend}/>);
    await screen.findByRole("heading", { name: "Local Release Console" });
    const first = (await backend.listProjects())[0]!;
    fireEvent.click(screen.getByRole("button", { name: "Settings" }));
    const capacity = await screen.findByLabelText("Front-row capacity") as HTMLInputElement;
    expect(capacity.value).toBe("4096");
    fireEvent.input(capacity, { target: { value: "8192" } });
    fireEvent.click(screen.getByLabelText("Teach on dismissed conflict"));
    fireEvent.click(screen.getByRole("button", { name: "Save memory settings" }));
    await screen.findByText("Memory settings saved for this project.");
    expect(await backend.memorySettings(first.id)).toEqual({ front_row_capacity: 8192, teach_on_conflict: false });
    fireEvent.click(screen.getByRole("button", { name: /new project/i }));
    await screen.findByRole("heading", { name: "New Project" });
    await waitFor(() => expect((screen.getByLabelText("Front-row capacity") as HTMLInputElement).value).toBe("4096"));
  });
  it("holds recovery import until verification and invalidates changed paths", async () => {
    const backend = new FakeDesktopBackend();
    const verify = vi.spyOn(backend, "verifyArchive");
    const backup = vi.spyOn(backend, "backupProject");
    const restore = vi.spyOn(backend, "importProject");
    render(<App backend={backend}/>);
    await screen.findByRole("heading", { name: "Local Release Console" });
    fireEvent.click(screen.getByRole("button", { name: "Settings" }));
    const importButton = () => screen.getByRole("button", { name: "Import verified recovery archive" }) as HTMLButtonElement;
    expect(importButton().disabled).toBe(true);
    expect(screen.getByText(/unencrypted—not redacted/)).toBeTruthy();
    fireEvent.click(screen.getByRole("button", { name: "Verify recovery archive" }));
    await waitFor(() => expect(importButton().disabled).toBe(false));
    fireEvent.input(screen.getByLabelText("Recovery directory"), { target: { value: "/tmp/another-archive" } });
    expect(importButton().disabled).toBe(true);
    verify.mockRejectedValueOnce(new Error("checksum mismatch"));
    fireEvent.click(screen.getByRole("button", { name: "Verify recovery archive" }));
    await screen.findByText(/checksum mismatch/);
    expect(importButton().disabled).toBe(true);
    expect(restore).not.toHaveBeenCalled();
    fireEvent.click(screen.getByRole("button", { name: "Create complete project backup" }));
    await screen.findByText(/Verified backup saved:/);
    expect(backup.mock.calls[0]![1]).toMatch(/^\/tmp\/another-archive-backup-\d+$/);
    fireEvent.click(screen.getByRole("button", { name: "Verify recovery archive" }));
    await waitFor(() => expect(importButton().disabled).toBe(false));
    fireEvent.click(importButton());
    await screen.findByRole("heading", { name: "Imported project" });
    expect(restore).toHaveBeenCalledWith("/tmp/another-archive");
  });
  it("requires prepare and explicit sent confirmation before local evaluation", async () => {
    const backend = new FakeDesktopBackend();
    const exchange = vi.spyOn(backend, "exchange");
    render(<App backend={backend}/>);
    await screen.findByRole("heading", { name: "Local Release Console" });
    fireEvent.click(screen.getByRole("button", { name: "Exchange" }));
    const evaluate = () => screen.getByRole("button", { name: "Evaluate diagnostic response and commit" }) as HTMLButtonElement;
    expect(evaluate().disabled).toBe(true);
    fireEvent.click(screen.getByRole("button", { name: "Prepare diagnostic packet" }));
    await screen.findByRole("button", { name: "Mark diagnostic turn sent" });
    expect(evaluate().disabled).toBe(true);
    fireEvent.click(screen.getByRole("button", { name: "Mark diagnostic turn sent" }));
    await waitFor(() => expect(evaluate().disabled).toBe(false));
    fireEvent.click(evaluate());
    await screen.findByText(/"result": "PASS"/);
    expect(evaluate().disabled).toBe(true);
    expect(exchange.mock.calls.map(call => call[1])).toEqual(["turn.prepare", "turn.sent", "response.evaluate"]);
  });
});
